import { ANIMATIONS } from '../types.d';

const DEFAULT_BACKDROP_MASK_COLOR = '#00000052';
const DEFAULT_HEIGHT = '50%';
const DEFAULT_ANIMATION = ANIMATIONS.SLIDE;
const DEFAULT_OPEN_ANIMATION_DURATION = 500;
const DEFAULT_CLOSE_ANIMATION_DURATION = 500;

export {
  DEFAULT_BACKDROP_MASK_COLOR,
  DEFAULT_HEIGHT,
  DEFAULT_ANIMATION,
  DEFAULT_OPEN_ANIMATION_DURATION,
  DEFAULT_CLOSE_ANIMATION_DURATION,
};
