import { ANIMATIONS } from "..";

const DEFAULT_BACKDROP_MASK_COLOR = '#000a';
const DEFAULT_HEIGHT = '50%';
const DEFAULT_ANIMATION = ANIMATIONS.SLIDE;

export {DEFAULT_BACKDROP_MASK_COLOR, DEFAULT_HEIGHT, DEFAULT_ANIMATION};
